### ISSUE TITLE
demo与 demo 3.3.14 都不能运行，加载不了动态

### ISSUE THREAD

**Issue by ooooknow** [JiyuShao/taro-dynamic-import-weapp#4]
![WechatIMG262](https://user-images.githubusercontent.com/26517533/147071114-66037b5a-c897-448e-a27f-7bf77cb21771.jpeg)

**Comment by ooooknow** [comment]
..

**Comment by lhkg1988** [comment]
这个是怎么解决的啊，我也报这个错误
